FROM node:22.6-alpine AS build

ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}

ARG VITE_REVERB_APP_KEY
ENV VITE_REVERB_APP_KEY=${VITE_REVERB_APP_KEY}

ARG VITE_REVERB_HOST
ENV VITE_REVERB_HOST=${VITE_REVERB_HOST}

ARG VITE_REVERB_PORT
ENV VITE_REVERB_PORT=${VITE_REVERB_PORT}

ARG VITE_REVERB_SCHEME
ENV VITE_REVERB_SCHEME=${VITE_REVERB_SCHEME}

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./ .

RUN npm run build

FROM nginx:1.25

RUN mkdir /app

COPY --from=build /app/dist /app

COPY deploy/remote/nginx.conf /etc/nginx/nginx.conf
